@ECHO OFF

:::::::::::::::
:: PARSING AVAILABLE BUILDS
REM SET INPUT_WHITELIST=%1
REM SET INPUT_WHITELIST=%INPUT_WHITELIST:"=%
SET "AVAILABLE_BUILDS="
setlocal EnableDelayedExpansion
SET "LOCAL_AVBUILDS="
FOR /F "tokens=* USEBACKQ" %%F IN (`DIR %~dp0 /a:d /B`) DO ( IF "%%F" neq "_tools" (
	IF "!LOCAL_AVBUILDS!" neq "" SET "LOCAL_AVBUILDS=!LOCAL_AVBUILDS!;"
	SET "LOCAL_AVBUILDS=!LOCAL_AVBUILDS!%%F"
) )
(
	endlocal
	SET AVAILABLE_BUILDS=%LOCAL_AVBUILDS%
)
REM ECHO %INPUT_WHITELIST%
REM ECHO %AVAILABLE_BUILDS%


REM FOR %%I in (%INPUT_WHITELIST%) DO (
REM 	FOR %%J in (%AVAILABLE_BUILDS%) DO (
REM 		IF %%I==%%J ECHO %%I
REM 	)
REM )

ECHO %AVAILABLE_BUILDS%
